### ISSUE TITLE
swaggerToTypeScriptClient is Generating Invalid Typscript

### ISSUE THREAD

**Issue by Jordantmcfar** [RSuter/NSwag#2039]
I am using version 12.0.17.

Error is: Types of property constructor are incompatible.

`export class CustomAttributeData implements ICustomAttributeData {
    attributeType?: string | undefined;
    constructor?: ConstructorInfo | undefined;
    constructorArguments?: CustomAttributeTypedArgument[] | undefined;
    namedArguments?: CustomAttributeNamedArgument[] | undefined;

    constructor(data?: ICustomAttributeData) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(data?: any) {
        if (data) {
            this.attributeType = data["attributeType"];
            this.constructor = data["constructor"] ? ConstructorInfo.fromJS(data["constructor"]) : <any>undefined;
            if (data["constructorArguments"] && data["constructorArguments"].constructor === Array) {
                this.constructorArguments = [] as any;
                for (let item of data["constructorArguments"])
                    this.constructorArguments!.push(CustomAttributeTypedArgument.fromJS(item));
            }
            if (data["namedArguments"] && data["namedArguments"].constructor === Array) {
                this.namedArguments = [] as any;
                for (let item of data["namedArguments"])
                    this.namedArguments!.push(CustomAttributeNamedArgument.fromJS(item));
            }
        }
    }

    static fromJS(data: any): CustomAttributeData {
        data = typeof data === 'object' ? data : {};
        let result = new CustomAttributeData();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["attributeType"] = this.attributeType;
        data["constructor"] = this.constructor ? this.constructor.toJSON() : <any>undefined;
        if (this.constructorArguments && this.constructorArguments.constructor === Array) {
            data["constructorArguments"] = [];
            for (let item of this.constructorArguments)
                data["constructorArguments"].push(item.toJSON());
        }
        if (this.namedArguments && this.namedArguments.constructor === Array) {
            data["namedArguments"] = [];
            for (let item of this.namedArguments)
                data["namedArguments"].push(item.toJSON());
        }
        return data; 
    }
}
![error](https://user-images.githubusercontent.com/48570965/54773781-a4229c80-4be0-11e9-9f31-b15e1a4465fe.png)
`

**Comment by RSuter** [comment]
Ref: https://github.com/RSuter/NJsonSchema/commit/65156d9bc3cc8c27a12db024eca84973fb99d09a

So the constructor name problem should be solved...
but here it seems that you are using an older TS version then the generated code?

**Comment by Jordantmcfar** [comment]
Great to hear; thanks RSuter!

I am using version 3.2.4 with version 2.7 specified in the nswag config.

**Comment by RSuter** [comment]
So if you rename `constructor?: ConstructorInfo | undefined` to `constructor`_?: ConstructorInfo | undefined` it is fine?

**Comment by Jordantmcfar** [comment]
It helped; but I still have these two issues:
![tojson](https://user-images.githubusercontent.com/48570965/54793473-f4b5ec00-4c18-11e9-8169-aa6457b3b883.png)
![customattri](https://user-images.githubusercontent.com/48570965/54793487-0a2b1600-4c19-11e9-9b96-fd9553b9bf55.png)

**Comment by RSuter** [comment]
I think this all will be fixed in the next version

**Comment by jeffgrizzle** [comment]
I think this all will be fixed in the next version

-> When is this scheduled for release?

**Comment by RSuter** [comment]
I hope today or tomorrow
