### ISSUE TITLE
The JSON property 'item' is defined multiple times on type 'System.Collections.ObjectModel.Collection

### ISSUE THREAD

**Issue by aadhi7** [RSuter/NSwag#755]
Target: .Net Framework 4.5.2

1. Create a C# class file as below 
namespace ClassLibrary1
{
    public class StringCollection : System.Collections.ObjectModel.KeyedCollection<string, string>
    {
        protected override string GetKeyForItem(string item)
        {
            //return some value
            return item;
        }
    }
}

2. Compile and create the dll
3. Run the NSwagStudio and load .Net Assembly (in Windows Machine) will get the exception as follows 

The JSON property 'item' is defined multiple times on type 'System.Collections.ObjectModel.Collection`1[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]'.

Stack Trace 

Server stack trace: 

   at NJsonSchema.Generation.JsonSchemaGenerator.<LoadPropertyOrFieldAsync>d__24.MoveNext() in C:\projects\njsonschema\src\NJsonSchema\Generation\JsonSchemaGenerator.cs:line 491
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NJsonSchema.Generation.JsonSchemaGenerator.<GeneratePropertiesAndInheritanceAsync>d__16.MoveNext() in C:\projects\njsonschema\src\NJsonSchema\Generation\JsonSchemaGenerator.cs:line 297
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NJsonSchema.Generation.JsonSchemaGenerator.<GenerateInheritanceAsync>d__19.MoveNext() in C:\projects\njsonschema\src\NJsonSchema\Generation\JsonSchemaGenerator.cs:line 344
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NJsonSchema.Generation.JsonSchemaGenerator.<GeneratePropertiesAndInheritanceAsync>d__16.MoveNext() in C:\projects\njsonschema\src\NJsonSchema\Generation\JsonSchemaGenerator.cs:line 302
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NJsonSchema.Generation.JsonSchemaGenerator.<GenerateInheritanceAsync>d__19.MoveNext() in C:\projects\njsonschema\src\NJsonSchema\Generation\JsonSchemaGenerator.cs:line 344
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NJsonSchema.Generation.JsonSchemaGenerator.<GeneratePropertiesAndInheritanceAsync>d__16.MoveNext() in C:\projects\njsonschema\src\NJsonSchema\Generation\JsonSchemaGenerator.cs:line 302
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NJsonSchema.Generation.JsonSchemaGenerator.<GenerateObjectAsync>d__15`1.MoveNext() in C:\projects\njsonschema\src\NJsonSchema\Generation\JsonSchemaGenerator.cs:line 268
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NJsonSchema.Generation.JsonSchemaGenerator.<GenerateAsync>d__10`1.MoveNext() in C:\projects\njsonschema\src\NJsonSchema\Generation\JsonSchemaGenerator.cs:line 139
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NJsonSchema.Generation.JsonSchemaGenerator.<GenerateAsync>d__9`1.MoveNext() in C:\projects\njsonschema\src\NJsonSchema\Generation\JsonSchemaGenerator.cs:line 100
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.SwaggerGeneration.AssemblyTypeToSwaggerGenerator.NetAssemblyLoader.<FromAssemblyTypeAsync>d__1.MoveNext() in C:\projects\nswag\src\NSwag.AssemblyLoaderCore\SwaggerGenerators\AssemblyTypeToSwaggerGenerator.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.SwaggerGeneration.AssemblyTypeToSwaggerGenerator.NetAssemblyLoader.FromAssemblyType(String[] classNames, String settingsData) in C:\projects\nswag\src\NSwag.AssemblyLoaderCore\SwaggerGenerators\AssemblyTypeToSwaggerGenerator.cs:line 91
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NSwag.SwaggerGeneration.AssemblyTypeToSwaggerGenerator.NetAssemblyLoader.FromAssemblyType(String[] classNames, String settingsData)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.SwaggerGeneration.AssemblyTypeToSwaggerGenerator.<GenerateAsync>d__2.MoveNext() in C:\projects\nswag\src\NSwag.AssemblyLoaderCore\SwaggerGenerators\AssemblyTypeToSwaggerGenerator.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.AssemblyTypeToSwaggerCommandBase.<<RunAsync>b__34_0>d.MoveNext() in C:\projects\nswag\src\NSwag.Commands\Commands\AssemblyTypeToSwaggerCommandBase.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.AssemblyTypeToSwaggerCommandBase.<RunAsync>d__34.MoveNext() in C:\projects\nswag\src\NSwag.Commands\Commands\AssemblyTypeToSwaggerCommandBase.cs:line 100
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.AssemblyTypeToSwaggerCommandBase.<RunAsync>d__33.MoveNext() in C:\projects\nswag\src\NSwag.Commands\Commands\AssemblyTypeToSwaggerCommandBase.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwagStudio.ViewModels.SwaggerGenerators.AssemblyTypeToSwaggerGeneratorViewModel.<<GenerateSwaggerAsync>b__34_1>d.MoveNext() in C:\projects\nswag\src\NSwagStudio\ViewModels\SwaggerGenerators\AssemblyTypeToSwaggerGeneratorViewModel.cs:line 150
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwagStudio.ViewModels.SwaggerGenerators.AssemblyTypeToSwaggerGeneratorViewModel.<<GenerateSwaggerAsync>b__34_0>d.MoveNext() in C:\projects\nswag\src\NSwagStudio\ViewModels\SwaggerGenerators\AssemblyTypeToSwaggerGeneratorViewModel.cs:line 148
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MyToolkit.Mvvm.ViewModelBase.<>c__DisplayClass15_0`1.<<RunTaskAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MyToolkit.Mvvm.ViewModelBase.<RunTaskAsync>d__12`1.MoveNext()

**Comment by bergziege** [comment]
Hi, is there a known workaround for this problem? I am getting the exact same thing on type 'System.IdentityModel.Tokens.SecurityTokenHandlerCollection'.

**Comment by RSuter** [comment]
I think this will be fixed with https://github.com/RSuter/NJsonSchema/issues/321

**Comment by RSuter** [comment]
Can you try with nswag v11 ci artifacts?

**Comment by AHorak** [comment]
System.InvalidOperationException: The JSON property 'Item' is defined multiple times on type 'System.Web.HttpApplicationStateBase'.

Same Problem with NSwag 11.12.16.0 (NSwagStudio)
NJSonSchema 9.10.19.0

Runtime: WinX64
Server stack trace: 
   bei NJsonSchema.Generation.JsonSchemaGenerator.<LoadPropertyOrFieldAsync>d__30.MoveNext()
--- Ende der Stapelberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel”st wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei NJsonSchema.Generation.JsonSchemaGenerator.<GeneratePropertiesAndInheritanceAsync>d__22.MoveNext()
--- Ende der Stapelberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel”st wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei NJsonSchema.Generation.JsonSchemaGenerator.<GenerateObjectAsync>d__15`1.MoveNext()
--- Ende der Stapelberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel”st wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei NJsonSchema.Generation.JsonSchemaGenerator.<GenerateAsync>d__10`1.MoveNext()
--- Ende der Stapelberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel”st wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei NJsonSchema.Generation.JsonSchemaGenerator.<GenerateAsync>d__9`1.MoveNext()
--- Ende der Stapelberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel”st wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei NJsonSchema.Generation.JsonSchemaGenerator.<GenerateWithReferenceAndNullability>d__13`1.MoveNext()
--- Ende der Stapelberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgel”st wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
...

**Comment by dotnetrules** [comment]
Hi all, having the same issue whenever our controllers return a JArray...
Error: The JSON property 'Item' is defined multiple times on type 'Newtonsoft.Json.Linq.JArray'.

**Comment by Johlandabee** [comment]
Alright, thanks for the hint. I'll try it tomorrow.

**Comment by stevehurcombe** [comment]
I'm getting the same error as @Johlandabee and I can't find any reference to HttpApplicationStateBase.

Is there likely to be a fix?

**Comment by RSuter** [comment]
Maybe a JArray? If the problem is JArray we should fix that (but its probably already fixed)

**Comment by statler** [comment]
Same issue in webAPI

        [HttpPut("UpdateControlLinePointSet")]
        public async Task<IActionResult> UpdateControlLinePointSet([FromBody] JArray pointSet)
        {
...
}

**Comment by RSuter** [comment]
Just tested this and it's indeed because JArray is wrongly processed.

**Comment by abhishekgoenka** [comment]
I am still getting the same error
![image](https://user-images.githubusercontent.com/14522198/44942594-def2ed80-add2-11e8-991b-e011a293e6cc.png)

I am on version **11.18.7.0**

**Comment by RSuter** [comment]
Can you create a new issue and provide a repro project?

**Comment by abhishekgoenka** [comment]
Moved to AutoRest. Works better then NSwag.

**Comment by abdelgrib** [comment]
If you have in your models (request or response) properties of type which inherits/implements types like `System.ComponentModel` (or other types) this will throw an error 

    "The JSON property 'item' is defined multiple times on type"...

Try to ignore this property using `[JsonIgnore]` attribute of `Newtonsoft.Json`

In my case i had a getter of type DataTable

**Comment by chrisjpryor** [comment]
> If you have in your models (request or response) properties of type which inherits/implements types like `System.ComponentModel` (or other types) this will throw an error
> 
> ```
> "The JSON property 'item' is defined multiple times on type"...
> ```
> 
> Try to ignore this property using `[JsonIgnore]` attribute of `Newtonsoft.Json`
> 
> In my case i had a getter of type DataTable



@RicoSuter I am experiencing this exact same issue with a `Datatable `property on one of my DTO's. Unfortunately I cannot just use `[JsonIgnore]` because I need to reference this property.
